import Navbar from '@/components/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
//Inter:Google Fontsからフォントを読み込むために使用。
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto p-4">
        <Navbar />
       
        <div className="mt-8">{children}</div>
        </div>
        </body>
    </html>
  );
}
//body:inter.className というクラス名が設定されています。これはGoogle Fontsから読み込んだフォントを適用するために使用されます。
//<Navbar />:コンポーネントが挿入されており、カスタムのナビゲーションバーが表示されます。
//{children} :プロパティが挿入されており、このコンポーネントの子要素が表示されます。通常、この部分にはページのコンテンツが表示されます。

